Add non-working ruby SDK example
Output from `make run`:

```
$ make run
docker buildx build --no-cache .
[+] Building 5.2s (10/10) FINISHED                                                                                                                                                                                                                                     docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                   0.0s
 => => transferring dockerfile: 191B                                                                                                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/ruby:3.1.3                                                                                                                                                                                                                          0.4s
 => CACHED [1/6] FROM docker.io/library/ruby:3.1.3@sha256:c4d28f375a0addcf2d6fc0ac59e1f2d9d6ed5a2531568c1b80c35627bcae5b21                                                                                                                                                             0.0s
 => [internal] load build context                                                                                                                                                                                                                                                      0.0s
 => => transferring context: 198B                                                                                                                                                                                                                                                      0.0s
 => [2/6] COPY Gemfile* ./                                                                                                                                                                                                                                                             0.0s
 => [3/6] COPY main.rb .                                                                                                                                                                                                                                                               0.0s
 => [4/6] RUN gem install bundler:2.5.22                                                                                                                                                                                                                                               1.1s
 => [5/6] RUN bundle install                                                                                                                                                                                                                                                           3.3s
 => ERROR [6/6] RUN ruby main.rb                                                                                                                                                                                                                                                       0.3s
------
 > [6/6] RUN ruby main.rb:
0.245 <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- eppo_client (LoadError)
0.245 	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
0.245 	from main.rb:1:in `<main>'
------
Dockerfile:8
--------------------
   6 |     RUN gem install bundler:2.5.22
   7 |     RUN bundle install
   8 | >>> RUN ruby main.rb
   9 |
--------------------
ERROR: failed to solve: process "/bin/sh -c ruby main.rb" did not complete successfully: exit code: 1
make: *** [run] Error 1
```